import os
plants= [
    "Monstera deliciosa",
    "Ficus elastica",
    "Ficus benjamina",
    "Zamioculcas zamiifolia",
    "Dracaena marginata",
    "Dracaena fragrans",
    "Nephrolepis exaltata",
    "Schefflera arboricola",
    "Sansevieria trifasciata",
    "Pilea peperomioides",
    "Schlumbergera",
    "Rhipsalidopsis",
    "Spathiphyllum",
    "Maranta leuconeura",
    "Calathea",
    "Anthurium",
    "Alocasia",
    "Epipremnum aureum",
    "Philodendron hederaceum",
    "Philodendron bipinnatifidum",
    "Hedera helix",
    "Kalanchoe blossfeldiana",
    "Yucca elephantipes",
    "Codiaeum variegatum",
    "Aspidistra elatior",
    "Crassula ovata",
    "Hoya carnosa",
    "Phalaenopsis",
    "Cactaceae",
    "Euphorbia milii",
    "Sansevieria cylindrica",
    "Fittonia",
    "Coffea arabica",
    "Chlorophytum comosum",
    "Chamaedorea elegans",
    "Dypsis lutescens",
    "Cocos nucifera",
    "Phoenix roebelenii",
    "Peperomia caperata",
    "Dieffenbachia",
    "Begonia rex",
    "Begonia semperflorens",
    "Nertera granadensis",
    "Cyclamen persicum",
    "Asparagus setaceus",
    "Ceropegia woodii",
    "Gynura",
    "Pachira aquatica",
    "Soleirolia soleirolii",
    "Tradescantia",
    "Ludisia discolor",
    "Spathiphyllum",
    "Guzmania",
    "Tillandsia",
    "Aeonium arboreum",
    "Aglaonema",
    "Erica",
    "Scindapsus pictus",
    "Nolina recurvata",
    "Echeveria elegans",
    "Sedum morganianum",
    "Haworthia",
    "Aeonium tabuliforme",
    "Adiantum capillus-veneris",
    "Strelitzia reginae",
    "Liriope muscari",
    "Oxalis triangularis",
    "Brighamia insignis",
    "Areca catechu",
    "Cissus rhombifolia",
    "Soleirolia",
    "Myrtus communis",
    "Saintpaulia",
    "Citrus hystrix",
    "Citrus limon",
    "Citrus sinensis",
    "Eucalyptus gunnii",
    "Nymphaea",
    "Asplenium nidus",
    "Camellia japonica",
    "Hypoestes phyllostachya",
    "Passiflora caerulea",
    "Laurus nobilis",
    "Salvia splendens",
    "Lantana camara",
    "Plumeria rubra",
    "Musa",
    "Streptocarpus",
    "Aeschynanthus",
    "Coleus",
    "Rhaphidophora tetrasperma",
    "Petunia",
    "Pelargonium",
    "Lobelia erinus",
    "Fuchsia",
    "Laurus",
    "Rosmarinus officinalis",
"Aloe vera",
    "Pandanus veitchii",
    "Tradescantia zebrina",
    "Cissus antarctica",
    "Ficus lyrata",
    "Plectranthus verticillatus (komarzyca)",
    "Chamaerops humilis",
    "Aspidistra elatior",
    "Cereus peruvianus",
    "Euphorbia tirucalli (roślina ołówkowa)",
    "Hoya kerrii",
    "Episcia cupreata",
    "Aglaonema commutatum",
    "Ctenanthe setosa",
    "Caladium bicolor",
    "Codiaeum variegatum (Kroton)",
    "Mimosa pudica (wrażliwa)",
    "Pachypodium lamerei (Madagaskarska palma)",
    "Rhipsalis baccifera",
    "Anthurium clarinervium",
    "Alocasia amazonica",
    "Begonia maculata",
    "Calathea lancifolia",
    "Calathea orbifolia",
    "Calathea makoyana",
    "Pilea glauca",
    "Chlorophytum amaniense (mandarynka)",
    "Zebrina pendula",
    "Dracena reflexa",
    "Syngonium podophyllum",
    "Dizygotheca elegantissima (falsyfikowana paproć)",
    "Soleirolia soleirolii (babie włosy)",
    "Platycerium bifurcatum (płaskla łosiorożna)",
    "Neoregelia carolinae",
    "Cryptanthus bivittatus",
    "Aechmea fasciata",
    "Bilbergia nutans",
    "Tillandsia cyanea",
    "Guzmania lingulata",
    "Vriesea splendens",
    "Beaucarnea recurvata (nolina)",
    "Euphorbia pulcherrima (gwiazda betlejemska)",
    "Strelitzia nicolai",
    "Euphorbia obesa",
    "Kalanchoe tomentosa",
    "Portulacaria afra",
    "Aptenia cordifolia",
    "Peperomia obtusifolia",
    "Peperomia rotundifolia",
    "Peperomia caperata 'Rosso'",
    "Aeonium haworthii",
    "Kalanchoe beharensis",
    "Rhipsalis cereuscula",
    "Sedum burrito (rozchodnik osiołka)",
    "Senecio rowleyanus (roślina koralikowa)",
    "Senecio herreianus (sznur bananów)",
    "Senecio radicans",
    "Crassula perforata",
    "Echeveria pulidonis",
    "Echeveria agavoides",
    "Adromischus cooperi",
    "Gasteria liliputana",
    "Pachyphytum compactum",
    "Faucaria tigrina",
    "Cotyledon tomentosa",
    "Conophytum bilobum",
    "Lithops",
    "Pleiospilos nelii",
    "Ardisia crenata",
    "Polyscias fruticosa",
    "Polyscias guilfoylei",
    "Bonsai (różne gatunki)",
    "Araucaria heterophylla (sosna norfolk)",
    "Coffea canephora",
    "Coffea liberica",
    "Asplenium scolopendrium",
    "Selaginella kraussiana",
    "Paphiopedilum (pantofelek Wenus)",
    "Oncidium (storczyk tańczący)",
    "Dendrobium",
    "Cattleya",
    "Miltoniopsis",
    "Brassia",
    "Cymbidium",
    "Vanda",
    "Masdevallia",
    "Doritaenopsis",
    "Cambria",
    "Paphiopedilum hybridum",
    "Tolumnia",
    "Bulbophyllum",
    "Ludisia discolor (storczyk klejnotowy)",
    "Vanilla planifolia (wanilia płaska)",
    "Aeschynanthus radicans",
    "Bougainvillea glabra",
    "Clivia miniata",
    "Medinilla magnifica",
    "Caladium hortulanum",
    "Erythrina crista-galli",
    "Bougainvillea spectabilis"
]

path = 'Dataset'

for plant in plants:
    plantpath = os.path.join(path, plant)
    os.makedirs(plantpath, exist_ok=True)
    print('Scraping plant', plant,'done')
